EPMRPP-84042 || Add parameters when import launches via API requests
reportportal/service-api pull request #1717
Opened 2023-06-21 12:42 UTC by APiankouski

2023-06-22 12:53 UTC, IvanKustau requested changes
And of course checkStyle

2023-06-22 14:05 UTC, APiankouski commented on src/main/java/com/epam/ta/reportportal/core/imprt/impl/AbstractImportStrategy.java
> +  }
Fixed

2023-06-22 14:37 UTC, rkukharenka approved these changes

2023-06-23 07:21 UTC, IvanKustau approved these changes

2023-06-23 08:20 UTC, merged